### ISSUE TITLE
Variant calling benchmark for customized dataset

### ISSUE THREAD

**Issue by ibseq** [hzi-bifo/Quasimodo#9]
Hi all
is there a particular structure/way to prepare custom data for quasimodo?
I run three variant callers and tried to run vareval but not sure what data/structure is missing
Or is quasimodo running the callers as part of benchmark?
Last, about 
"! Due to the high computational and time cost, by default this program do not run the whole benchmark for HCMV dataset from scratch (based on reads), instead it benchmarks the variant call and assembly based on the VCF files and scaffolds provided within this program under data directory." : how can we run from scratch using fastq.gz (where do we use the --slow parameter?)

Thanks, ibseq

**Comment by dawnmy** [comment]
Hi,

You need to prepare the VCFs generated by the variant callers you want to evaluate, and the reference genomes in the mixture. The `.fai` files should be generated in the same path as the reference genome `.fa` files. Then you can run the evaluation with:

```shell
python3 run_benchmark.py vareval -t 10 -c ~/miniconda3/envs \
        -v "<comma-separated list of VCF files>" \
        -r "<comma-separated list of reference genomes>" \
        -o <output directory>
```
The first given reference should be the one used to generate the VCFs.

**Comment by ibseq** [comment]
Hi
Thanks for the reply. Does it mean that —slow option cannot be used for custom data?
I also tried to use this one on your data, but the -s option seems not doing anything - as well as adjusting this on the config.yaml under runOnReads: true
How can I run the test data using the -s option?

Also, I have run my own vcf callers and saved the vcfs but:
1. In your example, the customize_data.yaml file does not list all the vcf files from each caller  vs each reference: which ones do I need to add to the list? : I only have one ref at the moment (do I need to index myslef? not running assemblers)

outpath: ../HCMV_bench_TM11_out # Please use different path for different input
vcfs: ../HCMV_benchmark_output/results/snp/callers/lofreq/TA-1-1.AD169.lofreq.vcf,../HCMV_benchmark_output/results/snp/callers/varscan/TA-1-1.AD169.varscan.vcf,../HCMV_benchmark_output/results/snp/callers/bcftools/TA-1-1.AD169.bcftools.vcf
scaffolds: data/assembly/abyss/TM-1-1.abyss.scaffolds.fa,data/assembly/idba/TM-1-1.idba.scaffolds.fa,data/assembly/megahit/TM-1-1.megahit.scaffolds.fa,data/assembly/metaspades/TM-1-1.metaspades.scaffolds.fa,data/assembly/ray/TM-1-1.ray.scaffolds.fa,data/assembly/savage/TM-1-1.savage.scaffolds.fa,data/assembly/spades/TM-1-1.spades.scaffolds.fa,data/assembly/tadpole/TM-1-1.tadpole.scaffolds.fa
refs: ref/Merlin.BAC.fa,ref/TB40E.GFP.fa
threads: 6

How long can it be the vcd list? 
Can I add a vcf generated by a caller not listed in the paper?
Is the customize_data.yaml being used for the test data?

Below my  failed tentatives:
(quasimodo) ibseq@ada02:~/Quasimodo$ python3 run_benchmark.py vareval -c ~/miniconda3 -t 20 -v "/ibseq/Quasimodo/vcf/snp/callers/freebayes/wwc006_freebayes.vcf.gz,/ibseq/Quasimodo/vcf/snp/callers/lofreq/wwc006_lofreq.vcf.gz,/ibseq/Quasimodo/vcf/snp/callers/varscan/wwc006_varscan.vcf.gz" -r "/ibseq/Quasimodo/ref/MN908947.3.fasta"
ValueError in line 11 of /ibseq/Quasimodo/eval_variant_custom.smk:
not enough values to unpack (expected 2, got 1)
  File "/ibseq/Quasimodo/eval_variant_custom.smk", line 11, in <module>
ERROR (/ibseq/Quasimodo/eval_variant_custom.smk)
2021-07-15 15:57        Could not unlock the working directory!
 
Traceback (most recent call last):
  File "run_benchmark.py", line 191, in run_snake
    raise Exception('Could not unlock the working directory!')
Exception: Could not unlock the working directory!
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "run_benchmark.py", line 226, in <module>
    cli()
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "run_benchmark.py", line 153, in vareval
    run_snake(variantcall_smk, dryrun, conda_prefix, **snake_kwargs)
  File "run_benchmark.py", line 214, in run_snake
    raise RuntimeError(e)
RuntimeError: Could not unlock the working directory!
(quasimodo) ibseq@ada02:~/Quasimodo$ 
 
 
(quasimodo) ibseq@ada02:~/QUASIMODO$ python3 ../Quasimodo/run_benchmark.py vareval -t 10 -c ~/miniconda3/ -v /ibseq/QUASIMODO/HCMV_benchmark_output/results/snp/callers/freebayes/wwc006_freebayes.vcf.gz,/ibseq/QUASIMODO/HCMV_benchmark_output/results/snp/callers/lofreq/wwc006_lofreq.vcf.gz,/ibseq/QUASIMODO/HCMV_benchmark_output/results/snp/callers/varscan/wwc006_varscan.vcf.gz -r /ibseq/QUASIMODO/HCMV_benchmark_output/ref/MN908947.3.fasta --dryrun
ValueError in line 11 of /ibseq/Quasimodo/eval_variant_custom.smk:
not enough values to unpack (expected 2, got 1)
  File "/ibseq/Quasimodo/eval_variant_custom.smk", line 11, in <module>
ERROR (/ibseq/Quasimodo/eval_variant_custom.smk)
2021-07-15 14:30        Could not unlock the working directory!
 
Traceback (most recent call last):
  File "../Quasimodo/run_benchmark.py", line 191, in run_snake
    raise Exception('Could not unlock the working directory!')
Exception: Could not unlock the working directory!
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "../Quasimodo/run_benchmark.py", line 226, in <module>
    cli()
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "../Quasimodo/run_benchmark.py", line 153, in vareval
    run_snake(variantcall_smk, dryrun, conda_prefix, **snake_kwargs)
  File "../Quasimodo/run_benchmark.py", line 214, in run_snake
    raise RuntimeError(e)
RuntimeError: Could not unlock the working directory!
(quasimodo) ibseq@ada02:~/QUASIMODO$ python3 ../Quasimodo/run_benchmark.py vareval -t 10 -c ~/miniconda3/ -v "wwc006_freebayes.vcf.gz,wwc006_lofreq.vcf.gz,wwc006_varscan.vcf.gz" -r "MN908947.3.fasta" --dryrun
ValueError in line 11 of /ibseq/Quasimodo/eval_variant_custom.smk:
not enough values to unpack (expected 2, got 1)
  File "/ibseq/Quasimodo/eval_variant_custom.smk", line 11, in <module>
ERROR (/ibseq/Quasimodo/eval_variant_custom.smk)
2021-07-15 14:32        Could not unlock the working directory!
 
Traceback (most recent call last):
  File "../Quasimodo/run_benchmark.py", line 191, in run_snake
    raise Exception('Could not unlock the working directory!')
Exception: Could not unlock the working directory!
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "../Quasimodo/run_benchmark.py", line 226, in <module>
    cli()
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "../Quasimodo/run_benchmark.py", line 153, in vareval
    run_snake(variantcall_smk, dryrun, conda_prefix, **snake_kwargs)
  File "../Quasimodo/run_benchmark.py", line 214, in run_snake
    raise RuntimeError(e)
RuntimeError: Could not unlock the working directory!
(quasimodo) ibseq@ada02:~/QUASIMODO$ python3 ../Quasimodo/run_benchmark.py vareval -t 10 -c ~/miniconda3/ -v "wwc006_freebayes.vcf.gz,wwc006_lofreq.vcf.gz,wwc006_varscan.vcf.gz" -r "MN908947.3.fasta"  -o wwc006_quasimodo
ValueError in line 11 of /ibseq/Quasimodo/eval_variant_custom.smk:
not enough values to unpack (expected 2, got 1)
  File "/ibseq/Quasimodo/eval_variant_custom.smk", line 11, in <module>
ERROR (/ibseq/Quasimodo/eval_variant_custom.smk)
2021-07-15 15:00        Could not unlock the working directory!
 
Traceback (most recent call last):
  File "../Quasimodo/run_benchmark.py", line 191, in run_snake
    raise Exception('Could not unlock the working directory!')
Exception: Could not unlock the working directory!
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "../Quasimodo/run_benchmark.py", line 226, in <module>
    cli()
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ibseq/miniconda2/envs/quasimodo/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "../Quasimodo/run_benchmark.py", line 153, in vareval
    run_snake(variantcall_smk, dryrun, conda_prefix, **snake_kwargs)
  File "../Quasimodo/run_benchmark.py", line 214, in run_snake
    raise RuntimeError(e)
RuntimeError: Could not unlock the working directory!

Thanks
BW
ibseq

**Comment by ibseq** [comment]
RuntimeError: Could not unlock the working directory!
what does it mean?

**Comment by dawnmy** [comment]
> RuntimeError: Could not unlock the working directory!
> what does it mean?

I think this means your previous task is still running and you can not run two tasks write to the same output at the same time.

**Comment by ibseq** [comment]
It only comes up when running the custom data…there are no other instances running

**Comment by dawnmy** [comment]
Could you describe the exact data you have for evaluation? It looks to me that you have one reference, and VCFs called based on the reference. Quasimodo is used to evaluate the haplotype assembly, and variant calling on strain or haplotype mixture datasets. The references should be the strain or haplotype genomes in the mixture. So our method might not be suitable for your data.

**Comment by ibseq** [comment]
I have a mixture of viruses within one sample - I am using one ref at the moment - but I will add more. The vcf was run using one ref at this stage.

**Comment by dawnmy** [comment]
How many viruses in one mixture? Generating VCF with one ref is fine for the pipeline. In the refs parameters (`-r`), you can put this one at the first position. The current pipeline only support two genome mixture. Will think about how to support three or more.

**Comment by ibseq** [comment]
We don’t know how many, as it is real data, but I’d expect at least two (wild type and mutated).

Having said this, I am still not able to run it: as I shown above, I did give list of vcf and ref but I’m getting same error. Any advice?

thanks again!
Ibseq

**Comment by dawnmy** [comment]
> It only comes up when running the custom data…there are no other instances running

Could you check the running processes with `ps fux` or `htop`? and then kill the processes related to Quasimodo. You can post the output of `ps fux` here, then I can tell which ones are related to Quasimodo. After this you can run the pipeline with two reference genomes.
